# Generated by Django 5.1 on 2024-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='youtub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('text', 'Text')], max_length=50)),
                ('file_path', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
